In [0]:
#함수를 선언한다. 
def sum(num1, num2) :
    result = num1+num2
    return result

# 함수를 호출한다.

num = sum(100, 200)
print(num)

In [0]:
def printInfo (name, job, age=20, address='서울') :
    print('이름:{}, 직업:{}, 나이:{}, 주소:{}'.format(name,job,age,address))
    
printInfo(name='이선화',job='강사')
printInfo(address='인천', name='강동원', job='배우')

In [0]:
def print_func(* num) :
    for i in num:
        print(i)

print_func('이선화','정우성','심은하', '박보검','강동원')

이선화
정우성
심은하
박보검
강동원

In [0]:
def printinfo(** info) :
    for a in info.keys() :
        print(info[a])

printinfo(name='이선화', job='강사', age=20)

이선화
강사
20

# 함수 실습

In [0]:
def sum(num1, num2):
    return num1+num2

print(sum(90, 250))

340

In [0]:
def avg_score(* score):
    tot= 0
    for i in score:
        tot = tot + i
    avg = tot / len(score)
    return avg

print(avg_score(90,80,43,84.100))

74.275